version: "3.8"

services:
  app:
    container_name: docker-react-container
    image: docker-react-image-2
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000